/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellTicketsRouteImport } from './routes/_shell.tickets'
import { Route as ShellResearchRouteImport } from './routes/_shell.research'
import { Route as ShellPlannerRouteImport } from './routes/_shell.planner'
import { Route as ShellMeetingsRouteImport } from './routes/_shell.meetings'
import { Route as ShellEmailRouteImport } from './routes/_shell.email'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellTicketsRoute = ShellTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResearchRoute = ShellResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlannerRoute = ShellPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMeetingsRoute = ShellMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEmailRoute = ShellEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/email': typeof ShellEmailRoute
  '/meetings': typeof ShellMeetingsRoute
  '/planner': typeof ShellPlannerRoute
  '/research': typeof ShellResearchRoute
  '/tickets': typeof ShellTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/email': typeof ShellEmailRoute
  '/meetings': typeof ShellMeetingsRoute
  '/planner': typeof ShellPlannerRoute
  '/research': typeof ShellResearchRoute
  '/tickets': typeof ShellTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/email': typeof ShellEmailRoute
  '/_shell/meetings': typeof ShellMeetingsRoute
  '/_shell/planner': typeof ShellPlannerRoute
  '/_shell/research': typeof ShellResearchRoute
  '/_shell/tickets': typeof ShellTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/research'
    | '/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/research'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/dashboard'
    | '/_shell/email'
    | '/_shell/meetings'
    | '/_shell/planner'
    | '/_shell/research'
    | '/_shell/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/tickets': {
      id: '/_shell/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof ShellTicketsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/research': {
      id: '/_shell/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ShellResearchRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/planner': {
      id: '/_shell/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof ShellPlannerRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/meetings': {
      id: '/_shell/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof ShellMeetingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/email': {
      id: '/_shell/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof ShellEmailRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellEmailRoute: typeof ShellEmailRoute
  ShellMeetingsRoute: typeof ShellMeetingsRoute
  ShellPlannerRoute: typeof ShellPlannerRoute
  ShellResearchRoute: typeof ShellResearchRoute
  ShellTicketsRoute: typeof ShellTicketsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellEmailRoute: ShellEmailRoute,
  ShellMeetingsRoute: ShellMeetingsRoute,
  ShellPlannerRoute: ShellPlannerRoute,
  ShellResearchRoute: ShellResearchRoute,
  ShellTicketsRoute: ShellTicketsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
